[package]
description = "`mlang` is a programming language to define declarative programming language."
documentation = "https://docs.rs/vglang"
license = "MIT"
name = "mlang"
edition = "2021"
repository = "https://github.com/vglang/mlang"
version = "0.1.2"

[dependencies]
thiserror = "^2.0"
log = "^0.4"
pretty_env_logger = "^0.5"
serde = { version = "^1.0", features = ["derive"], optional = true }
nom_locate = "^4"
nom = "^7"

[features]
default = ["serde"]
serde = ["dep:serde"]
