[package]
description = "Standard and official integration test suite for vglang."
documentation = "https://docs.rs/vglang-spec"
license = "MIT"
name = "vglang-spec"
edition.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
vglang = { workspace = true, features = ["serde", "sexpr"] }
heck = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
