[package]
description = "`vglang` is a simple and fast **Vector Graphics programming Language**."
documentation = "https://docs.rs/vglang"
license = "MIT"
name = "vglang"
edition.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
vglang-derive = { workspace = true, optional = true }
concat-idents = { workspace = true }

[features]
default = ["serde", "sexpr", "surface"]
serde = ["dep:serde"]
sexpr = ["vglang-derive/sexpr", "surface"]
surface = []
