[package]
description = "Simple and fast vector graphics language (vglang)"
documentation = "https://docs.rs/vglang"
edition.workspace = true
name = "vglang"
repository.workspace = true
version.workspace = true

[dependencies]
thiserror = {workspace = true}

log = {workspace = true, optional = true}
parserc = {workspace = true, optional = true}
serde = {workspace = true, optional = true}
xml-builder = {workspace = true, optional = true}

[build-dependencies]
vglang-metadata = {workspace = true, features = ["codegen"]}

[dev-dependencies]
divan = {workspace = true}
nom = {workspace = true}

[features]
binary = []
lang = ["parserc", "log"]
serde = ["dep:serde", "parserc/serde"]
sexpr = []
surface = []
svg = ["surface", "xml-builder"]
