[package]
description = "Simple and fast vector graphics language (vglang)"
documentation = "https://docs.rs/vglang"
name = "vglang"

[package.edition]
workspace = true

[package.repository]
workspace = true

[package.version]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.vglang-derive]
workspace = true

[dependencies.log]
optional = true
workspace = true

[dependencies.serde]
optional = true
workspace = true

[dependencies.parserc]
optional = true
workspace = true

[dev-dependencies.pretty_env_logger]
workspace = true

[dev-dependencies.divan]
workspace = true

[build-dependencies.mlang]
features = ["codegen"]
workspace = true

[features]
default = ["serde", "lang"]
lang = ["parserc", "log"]
serde = ["dep:serde"]

[[bench]]
harness = false
name = "color"

[[bench]]
harness = false
name = "num"
