[package]
description = "Simple and fast vector graphics language (vglang)"
documentation = "https://docs.rs/vglang"
edition.workspace = true
name = "vglang"
repository.workspace = true
version.workspace = true

[dependencies]
thiserror = {workspace = true}

log = {workspace = true, optional = true}
parserc = {workspace = true, optional = true}
serde = {workspace = true, optional = true}

[dev-dependencies]
divan = {workspace = true}

[features]
default = ["serde", "lang"]
lang = ["parserc", "log"]
serde = ["dep:serde", "parserc/serde"]

[[bench]]
harness = false
name = "color"

[[bench]]
harness = false
name = "num"
